services:
  api:
    image: docker-api
    build:
      context: ../../api
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
      keycloak:
        condition: service_started
    environment:
      UVICORN_HOST: 0.0.0.0
      UVICORN_PORT: "8000"
      PGHOST: db
      PGPORT: "5432"
      PGDATABASE: appdb
      PGUSER: postgres
      PGPASSWORD: postgres
      REDIS_URL: redis://redis:6379/0
      S3_ENDPOINT: http://minio:9000
      S3_BUCKET: aisoftlogic
      S3_ACCESS_KEY: minioadmin
      S3_SECRET_KEY: minioadmin
      KEYCLOAK_URL: http://keycloak:8081
    ports: [ "8000:8000" ]
    networks: [ default ]

  web:
    image: docker-web
    build:
      context: ../../web
      dockerfile: Dockerfile
    depends_on:
      api:
        condition: service_started
      minio:
        condition: service_healthy
      keycloak:
        condition: service_started
    environment:
      HOSTNAME: 0.0.0.0
      PORT: "3000"
      NEXT_PUBLIC_API_URL: http://api:8000
      NEXT_PUBLIC_KEYCLOAK_URL: http://keycloak:8081
      NEXT_PUBLIC_KEYCLOAK_REALM: aisoftlogic-dev
      NEXT_PUBLIC_KEYCLOAK_CLIENT_ID: web-client
    ports: [ "3000:3000" ]
    networks: [ default ]
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:3000/ || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 10s

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: [ "5432:5432" ]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s

  redis:
    image: redis:7
    ports: [ "6379:6379" ]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 5s

  minio:
    image: minio/minio
    command: ["server", "--console-address", ":9001", "/data"]
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:9000/minio/health/ready >/dev/null || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 10s

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.6
    command: ["start-dev", "--http-port=8081", "--spi-login-protocol-openid-connect-legacy-logout-redirect-uri=true"]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports: [ "8081:8081" ]
    # (no healthcheck; we wait via curls in smoke.sh)

networks:
  default: {}