name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  api:
    name: API (pytest)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}/api
        run: pytest -q

  web:
    name: Web (vitest)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1) Install pnpm first so setup-node can use it for caching
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.14.0
          run_install: false    # we'll install after caching is set up

      # 2) Now setup Node and enable pnpm cache (this calls `pnpm store path`)
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: pnpm
          cache-dependency-path: web/pnpm-lock.yaml

      # 3) Install deps
      - name: Install dependencies
        run: pnpm install --frozen-lockfile=false

      # 4) Run tests
      - name: Run vitest
        env:
          NODE_ENV: test
          CI: "true"
        run: pnpm vitest run